##############################################################################
# H2 콘솔 사용 여부
spring.h2.console.enabled=true

# H2 데이터베이스 관리 화면에 접속하는 URL 경로
# http://localhost:8080/h2-console
spring.h2.console.path=/h2-console

# 스프링이 접속할 H2 데이터베이스의 주소
# 생성되는 파일 이름: local.mv.db 
spring.datasource.url=jdbc:h2:~/local

# 자바가 H2 데이터베이스에 접속할 수 있게 해주는 프로그램
spring.datasource.driverClassName=org.h2.Driver

# 데이터베이스의 사용자명 (기본값은 sa)
spring.datasource.username=sa

# 데이터베이스의 비밀번호
spring.datasource.password=
##############################################################################
# Hibernate가 H2 문법에 맞는 SQL을 생성
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# 엔티티에 맞게 데이터베이스 테이블을 자동으로 생성하거나 수정
spring.jpa.hibernate.ddl-auto=update
##############################################################################
# format_sql=true  → Hibernate가 출력하는 SQL을 보기 좋게 정렬
spring.jpa.properties.hibernate.format_sql=true

# show_sql=true    → Hibernate가 실행한 SQL을 콘솔에 출력
spring.jpa.properties.hibernate.show_sql=true
##############################################################################